### ISSUE TITLE
ARM Containers

### ISSUE THREAD

**Issue by bdsoha** [flungo-docker/avahi#3]
Hello,

Any chance there's going to be an `arm` compatible image?

Thanks.

**Comment by si458** [comment]
i second this 👍

**Comment by flungo** [comment]
Happy to add this but need to find the time to adapt the Dockerfile to build for multiple architectures and then test. Shouldn't be a problem as the base image has an ARM image and the script won't be specific to the architecture.

PRs welcome otherwise I'll update once I have an image pushed for wider testing.

**Comment by flungo** [comment]
Apologies for the delay. Turns out that it seems to work without modification, it just needed to be built for the right architecture. I have now pushed [flungo/avahi:multiarch](https://hub.docker.com/layers/flungo/avahi/multiarch/images/sha256-f6aebf333d45571c40cb871b3e7a96c9da88fdef52a6dc4f6259ce2d8682fd44?context=repo) which has support for `linux/arm64`. I have confirmed that it runs, but haven't yet had the chance to test them in a real-world application. I can't see why not but feedback will be great.

If you do have issues, you can also try building the image yourself:

```bash
git clone https://github.com/flungo-docker/avahi.git docker-avahi
cd docker-avahi
docker build -t flungo/avahi:arm src
```

I will try to test this for the mDNS reflection use case in the new year.

**Comment by autodeck** [comment]
> Apologies for the delay. Turns out that it seems to work without modification, it just needed to be built for the right architecture. I have now pushed [flungo/avahi:multiarch](https://hub.docker.com/layers/flungo/avahi/multiarch/images/sha256-f6aebf333d45571c40cb871b3e7a96c9da88fdef52a6dc4f6259ce2d8682fd44?context=repo) which has support for `linux/arm64`. I have confirmed that it runs, but haven't yet had the chance to test them in a real-world application. I can't see why not but feedback will be great.
> 
> If you do have issues, you can also try building the image yourself:
> 
> ```bash
> git clone https://github.com/flungo-docker/avahi.git docker-avahi
> cd docker-avahi
> docker build -t flungo/avahi:arm src
> ```
> 
> I will try to test this for the mDNS reflection use case in the new year.

Works great for me on my rpi with macvlan. I can see my printer and Chromecasts across vlans.

Thanks 👍

**Comment by flungo** [comment]
A GitHub workflow has been set up which will keep all of the tags on DockerHub up to date with multi-arch support.
